---

- name: Test NginX ports
  wait_for:
    port: "{{ item }}"
    host: "{{ ansible_default_ipv4.address }}"
    timeout: 120
    msg: "Check Nginx ports"
  with_items:
    - "{{ nginx_http_port }}"
    - "{{ nginx_https_port }}"
  tags: rundeck,nginx,test
